### PR TITLE
Add support for /v2/events stream

### PR DESCRIPTION
**Pull request by nuclon**
The PR allows to use event stream from Marathon REST API added in v0.9.0

### CODE REVIEW

**Comment by solarkennedy** [comment]
Hmm. This is kinda new and different. Can you add an itest for it? 
Also setup.py probably needs to change.

**Comment by solarkennedy** [comment]
Thank you. Long term, if you need this feature to continue to work as marathon evolves, it needs to have a section in the actual itest code that actually tries to read the events and maybe asserts that there is like, something? 

But this technically isn't a blocker to merging.

My last request is that you rebase, I merged in a bunch of pep8 fixes.

**Comment by nuclon** [comment]
Hi,
I've added actual itest code. I take some time to make it working on mac, but it works now.

**Comment by solarkennedy** [comment]
Ok, the last thing to do is to bring it up to pep8 compliance. Check out the flake8 issues in an example travis run: https://travis-ci.org/thefactory/marathon-python/jobs/123588467

Or run tox -e pep8

**Comment by nuclon** [comment]
Tests are failing on marathon waiting timeout.

**Comment by nuclon** [comment]
It looks like the feature isn't really supported till 0.11.0 due to https://github.com/mesosphere/marathon/issues/1926
so I updated tests to run starting from 0.11.0 and above

**Comment by solarkennedy** [comment]
This looks great to me. Thank you very much for iterating through the tests and pep8 and all the things. Thanks!

**Pull request merged**
