### PR TITLE
travis should run unit tests

### PR DESCRIPTION
**Pull request by Rob-Johnson**

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you make it run tests first so we fail faster?

**Comment by Rob-Johnson** [comment]
done.

**Comment by solarkennedy** [comment]
Well... mesosphere's apt repos have a checksum mismatch....
But the test step passed!

**Comment by solarkennedy** [comment]
I'm going to go ahead and merge this in because we are seeing real breakage that these unit tests would have covered. Travis will sort itself out eventually.

**Comment by Rob-Johnson** [comment]
thanks!

**Pull request merged**
