### PR TITLE
Use the /v2/tasks/delete endpoint for taskkill

### PR DESCRIPTION
**Pull request by fengyehong**
Implement this:
https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-tasks-delete

In fact, as function name `kill_task` and `kill_tasks` both occupied, I'm not sure how to name it.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Seems legit. How do you feel about... tests?

**Comment by fengyehong** [comment]
Test added.

**Comment by solarkennedy** [comment]
I've got a related, but I guess not really overlapping PR #72.

**Comment by fengyehong** [comment]
I noticed it.
Maybe I can do a little rebase after PR#72 merged.

**Comment by fengyehong** [comment]
Rebased this.

**Comment by solarkennedy** [comment]
This is good, thank you for rebasing. I am also not really what to really call it, this name is good as any if you ask me.

**Pull request merged**
