### PR TITLE
Don't drop 0s when transforming to JSON

### PR DESCRIPTION
**Pull request by iksaif**
This fixes issue #75

### CODE REVIEW

**Comment by solarkennedy** [comment]
Cool cool. Hang tight I've got a fix for the tests coming and I'll ask you to merge/rebase.

**Comment by solarkennedy** [comment]
Ok itests are fixed in master, please merge/rebase and let's see the results.

**Comment by iksaif** [comment]
I rebased but it still seems to fail. I didn't find the link to see which test fails exactly. Do you have it?
(Note: feel free to just copy my patch if it's easier).

**Comment by solarkennedy** [comment]
You can click on the red X in the pull request to see the output of the tests. Only one part of the matrix failed, I re-ran it but I'm sure it is fine. This fix is also in #77 but I'll go ahead and merge this in.

Thanks!

**Pull request merged**
