### PR TITLE
a small fix for fetching apps for marathon v0.15

### PR DESCRIPTION
**Pull request by burakbostancioglu**

### CODE REVIEW

**Comment by burakbostancioglu** [comment]
@mbabineau Could you pls review this ? Its just a small fix for marathon v0.15 while fetching apps.

**Comment by solarkennedy** [comment]
Looks fine. Thank you. Longer term, feel free to put in .15 PRs with expanded support in the .travis matrix.

**Comment by brouberol** [comment]
Do you have an estimate of when this patch will be released to PyPI? I currently have to vendor the master.zip in my project because my CI env does not have access to github, and I'm quite eager to get rid of this abomination :)

Cheerio

**Comment by solarkennedy** [comment]
I've release 0.7.7.

**Comment by brouberol** [comment]
Thank you very much!


On Mon, Feb 29, 2016, at 04:55 PM, Kyle Anderson wrote:
> I've release 0.7.7.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/thefactory/marathon-python/pull/87#issuecomment-190266928

**Pull request merged**
