### PR TITLE
Update schema for App and Task: add versionInfo and slaveId (Marathon v11)

### PR DESCRIPTION
**Pull request by nathanleiby**
See release notes for this API change: https://github.com/mesosphere/marathon/releases/tag/v0.11.0

"We now have versionInfo with lastConfigChangeAt and lastScalingAt in the
apps JSON of our API." (ee2c5a4)

"Marathon now saves the slaveID of newly launched tasks." (b832dd6)

### CODE REVIEW

**Comment by solarkennedy** [comment]
Cool! Can you expand the matrix in the travis.yaml to be sure it will actually work against that version of marathon?

**Comment by nathanleiby** [comment]
@solarkennedy expanded the matrix but in v11 build it's failing due to 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: mesosphere/marathon/Main : Unsupported major.minor version 52.0
```

I think this is because Marathon v11 has a breaking change re: Java

```
Breaking Changes

Java 8 or higher is needed to run Marathon, since Java 6 and 7 support has reached end of life.
```

**Comment by solarkennedy** [comment]
Gotcha. Can you bump the version of java installed so that we can properly test against marathon 11?

**Comment by itamaro** [comment]
Hi, what's the status of this PR?

I'm working with a client lib built from this fork because I'm working against Marathon 0.11.1, so it doesn't work without it. I can confirm that it works fine, but definitely would rather see it merged :-)

**Comment by solarkennedy** [comment]
Look like it has stalled. @itamaro if it is blocking you can you pick it up and make the tests pass? Otherwise I'll work on it in a couple of weeks as we upgrade.

**Comment by itamaro** [comment]
I wish I could, @solarkennedy, but I can't figure out why it's failing.

Looking at the logs of [this failure](https://travis-ci.org/thefactory/marathon-python/jobs/84362730), looks like it's using jdk-9, which should be fine IIUC.

Trying to recreate this locally for further debugging (running `make itests` or `MARATHONVERSION=0.11.0 make itests` on an ubuntu 14.04 box with Docker), I get other errors:

```
The following packages have unmet dependencies:
 marathon : Depends: java8-runtime-headless but it is not installable
E: Unable to correct problems, you have held broken packages.
Service 'marathon' failed to build: The command '/bin/sh -c /root/install-marathon.sh' returned a non-zero code: 100
ERROR: InvocationError: '/bin/bash -c [[ -n $TRAVIS ]] || docker-compose build'
________________________________________________________________________________________ summary ________________________________________________________________________________________
ERROR:   itests: commands failed
make: *** [itests] Error 1
```

So I'll appreciate assistance with dealing with this, or I'll wait for you to get to it, as I can keep using this branch until then.

**Comment by nathanleiby** [comment]
Sorry to drop this. Thank you for following up on the fix!

**Pull request closed without merging**
