### PR TITLE
Added two app parameters - tasks_healthy, tasks_unhealthy (marathon-0.8.1-RC2)

### PR DESCRIPTION
**Pull request by pradeepchhetri**

### CODE REVIEW

**Comment by mbabineau** [comment]
:+1: thanks!

**Comment by bacoboy** [comment]
Can we get a released version cut to incorporate the 0.8.1 attributes please?

**Comment by mbabineau** [comment]
Done: https://github.com/thefactory/marathon-python/releases/tag/0.6.13

**Comment by bacoboy** [comment]
Sweet!  Thanks.

**Pull request merged**
