### PR TITLE
make models.info compatible with 1.4.9

### PR DESCRIPTION
**Pull request by iandyh**
Recently we updated our Marathon from 1.1.1 to 1.4.9,  the missing keyword argument will break the client when it connects to Marathon.

I've not found other compatibility issues with 1.4.9 so far. 

Thanks for reviewing.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you make the tests green, and also add 1.4.9 to the travis matrix?

**Comment by iandyh** [comment]
@solarkennedy Hi. Sorry for the late reply. I've made the tests passed.

**Comment by solarkennedy** [comment]
Can you add 1.4.9 to the travis.yaml so we test against this version continuously?

**Comment by solarkennedy** [comment]
Sorry, what I meant to say was "can you replace 1.4.7 with 1.4.9".

We don't need to test against every minor point release, just the latest for each.

**Comment by iandyh** [comment]
@solarkennedy Hello. Is this what you meant?

**Comment by solarkennedy** [comment]
Yes. Thank you.

**Comment by iandyh** [comment]
Thanks!

**Pull request merged**
