### PR TITLE
Make `force_pull_image` actually work

### PR DESCRIPTION
**Pull request by mattrobenolt**
Should be pretty self explanatory, but #31 wasn't enough to make it work.

### CODE REVIEW

**Comment by mbabineau** [comment]
:+1: thank you sir

**Comment by mattrobenolt** [comment]
@mbabineau Mind cutting a release of this since marathon 0.8.2 was released today? That means we can use this feature now. :)

**Comment by mbabineau** [comment]
Here you go: 93c8d8a / `0.6.15`

**Comment by solarkennedy** [comment]
Thanks :)

**Pull request merged**
