### PR TITLE
Case for 503 reponse

### PR DESCRIPTION
**Pull request by jonaubf**
In case, when we got 503, content of response from marathon is not json

```
[ERROR] Got HTTP 503: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 503 </title>
</head>
<body>
<h2>HTTP ERROR: 503</h2>
<p>Problem accessing /v2/tasks. Reason:
<pre>    Could not determine the current leader</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>
</body>
</html>
```

### CODE REVIEW

**Comment by Rob-Johnson** [comment]
lg2m - could you please write a test? There are examples you can follow in the tests directory

**Comment by jonaubf** [comment]
test added, conflicts resolved

**Comment by Rob-Johnson** [comment]
@jonaubf your tests aren't passing; you can run 'tox' locally to reproduce

**Comment by solarkennedy** [comment]
@jonaubf I still like this change. Can you address the failing tests?

**Comment by solarkennedy** [comment]
We are now catching this in #178

**Pull request closed without merging**
