### PR TITLE
Feature/marathon constraint model improvements

### PR DESCRIPTION
**Pull request by diogommartins**
- Adding tests to `MarathonConstraint` methods
- Adding `MarathonConstraint.from_string` classmethod

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you address the lint failures?

**Comment by diogommartins** [comment]
Fixed

**Comment by diogommartins** [comment]
Is there something else you want me to do?

**Comment by solarkennedy** [comment]
Nope! Thank you.

**Pull request merged**
