### PR TITLE
added clazz arg to get_app(in some cases we use class which extends M…

### PR DESCRIPTION
**Pull request by d-ganchar**
Possibility to set class type to get_app

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you tell me a little bit more about your use-case?

**Comment by d-ganchar** [comment]
Of course. I try to explain. For example I have custom class which extends MarathonApp:

```
from marathon.models import MarathonApp

class MyMarathonApp(MarathonApp):
    """
    Additional methods, properties, overriding something etc...
    """

example_app = MyMarathonApp()
# do something with our app...
# and now we need to create or update our app using MarathonClient
marathon_client.create_app('/test/app/id', example_app)
marathon_client.update_app('/test/app/id', example_app)
# after this we try to get our app:
app = marathon_client.get_app('/test/app/id') 
# app variable is instance of MarathonApp, but not MyMarathonApp
```

Of course, we can override get_app and set class to _parse_response. But I think this is not a flexible solution. Do you agree with me?

**Comment by solarkennedy** [comment]
I don't know, as I've never see anyone use the methods of a python module and insert their own objects in this way. Why should python-marathon return an object that we don't control? Seems a lot more sane for the marathon-python module to only operate on internal objects.

I think it is fine for users of this module to make objects that inherit from MarathonApp, but I don't think it is a good idea to tangle the modules like this.

What if you had a function that was called `MyMarathonApp.import_marathon_app(client.get_app('foo'))`? It is a little more verbose, but a lot more obvious what is going on?

**Comment by d-ganchar** [comment]
`Why should python-marathon return an object that we don't control?`
I'm agree with you. But for this case I can add next condition to get_app like this:

```
def get_app(self, app_id, embed_tasks=False, embed_counts=False,
                embed_deployments=False, embed_readiness=False,
                embed_last_task_failure=False, embed_failures=False,
                embed_task_stats=False,
                clazz=MarathonApp):
    if not issubclass(clazz, MarathonApp):
          raise MarathonError('Invalid argument "clazz"')
    ...
```

Or you do not like this solution? It will be clear.

**Comment by Rob-Johnson** [comment]
+1 for @solarkennedy's idea here - personally I think this should be done from the wrapper class. I'd do this as something like:

```
app = marathon_client.get_app('/test/app/id') 
my_app = MyMarathonApp.from(app)
```

If you want to support this type of casting, you'll have to do it for *every* model in the library.

**Comment by d-ganchar** [comment]
Ok. Thanks for conversation.

**Pull request closed without merging**
