### PR TITLE
implement __eq__ on base models + fix tests to be useful

### PR DESCRIPTION
**Pull request by Rob-Johnson**
the test that I submitted in #53 wasn't actually asserting anything - just that it didn't blow up like it did before. This makes sure that we're actually checking equality of the objects returned.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you merge master so we can *actually* see the results in travis?

Also, I don't really understand why the unit test wasn't asserting anything. Isn't this that the *parse* level, so simply listing deployment would have invoked the bug right?

Although I do appreciate the stronger assertion.

**Comment by Rob-Johnson** [comment]
ok - I've merged master in so we should see the output in travis now.

True that we were originally just checking that we could parse the response properly, but we've now got stronger assertions about the objects that are produced rather than just 'it doesn't blow up'.

**Comment by solarkennedy** [comment]
I'm trying to run the itests manually to verify your patch works on the itests

**Comment by solarkennedy** [comment]
I ran the itests manually and this is fine.

**Comment by solarkennedy** [comment]
Sorry @Rob-Johnson. While this does pass on the unit+itests here, it fails on our Yelp itest in our restart code.

I'm not going to revert this, as I know this functionality was broken before anyway, but there is still something not right.

I'll update our internal ticket with as much context as I can, and I'll *try* to figure it out for myself if possible. (but this is a tricky thing to catch)

If I really need to I'll copy over *more* of our itest coverage into here, specifically the failing test we have (serviceinit restart)

**Pull request merged**
