### PR TITLE
NOJIRA marathon 0.14.0 support

### PR DESCRIPTION
**Pull request by dilyn**

### CODE REVIEW

**Comment by vito-c** [comment]
+1

**Comment by chrishaessig** [comment]
LGTM

**Comment by solarkennedy** [comment]
Can you also expand the .travis.yaml to include marathon .14 support?

It looks like all the tests are passing... my best guess here is that we are pulling off of the mesossphere repos and the new version of mesos isn't compatible with the versions of marathon we are testing against. I'll come up with a fix for that and have you merge/rebase master.

**Comment by solarkennedy** [comment]
Ok itests are fixed in master, please merge/rebase and let's see the results.

Also please add the new entry for marathon .14. At the same time please remove the next oldest version (0.8.1?) so we don't grow the matrix.

**Comment by lcjlcj** [comment]
I ran into this because marathon 0.14.0 added ipAddress in MarathonApp response. Mesos 0.26.0, marathon 0.14.0. Marathon-python 0.7.5.

  File "/usr/local/lib/python2.7/dist-packages/marathon/client.py", line 104, in create_app
    return self._parse_response(response, MarathonApp)
  File "/usr/local/lib/python2.7/dist-packages/marathon/client.py", line 47, in _parse_response
    return clazz.from_json(target)
  File "/usr/local/lib/python2.7/dist-packages/marathon/models/base.py", line 34, in from_json
    return cls(**{to_snake_case(k): v for k,v in attributes.items()})
TypeError: __init__() got an unexpected keyword argument 'ip_address'

**Comment by solarkennedy** [comment]
Obsoleted by #85

**Pull request closed without merging**
