### PR TITLE
coerce all args to text

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by solarkennedy** [comment]
@mattrobenolt the itests are failing right now due to an apt problem.

I ran the tests locally and they did pass, but they were not failing before.

Can you add a failing itest for this to prevent a regression in the future? Apparently we were not testing for this.

**Comment by mattrobenolt** [comment]
Yeah, it looks like tests are pretty sparse as-is and this is a weird framework. Can you point me in the right direction and I'll happily add them. I initially was going to, then gave up because I was confused. :)

**Comment by solarkennedy** [comment]
Yes!

Your code hint is
https://github.com/thefactory/marathon-python/blob/89ba80506dfce36109e29e63c8dbc5fd98322af2/itests/steps/marathon_steps.py#L28

**Comment by mattrobenolt** [comment]
Going to wait until #57 because this patch breaks python3 compatibility anyways. TIL this was updated to support python3. :heart:

**Comment by mattrobenolt** [comment]
This diff is now based on my unicode diff, so that must precede.

**Comment by solarkennedy** [comment]
@mattrobenolt Is this still relevant?

**Comment by mattrobenolt** [comment]
@solarkennedy I have no idea, I haven't used Marathon in about a year now. :)

**Comment by solarkennedy** [comment]
Ok I'm going to close for now.

**Pull request closed without merging**
