### PR TITLE
Modify list_apps so user can input app_id without the starting slash

### PR DESCRIPTION
**Pull request by fengyehong**
I want to write code like `client.list_tasks("my-test-app")` to get task list, but by now i get an empty list

### CODE REVIEW

**Comment by fengyehong** [comment]
hi, any comments?

**Comment by solarkennedy** [comment]
I'm not really sure. This changed early back in like, Marathon .7 or something when they started doing "groups". At Yelp we do what you have done but at a higher level.

I'm not sure if the role of this library is to "hide" these kind of things from the consumers. I kinda see this library as more of a direct connection to the API. If the api needs a leading slash, so be it, if it returns a trailing slash, then the library should return it?

**Comment by fengyehong** [comment]
I see no harm of doing this, it won't break any thing. It's only an convenience for users who don't use Marathon "group" feature.

Marathon can deal with app path starting or not starting with a slash, it's not a mandatory to input app path with a leading slash. Marathon map `my-test-app` to `/my-test-app`

So I think marathon-python library can take care of this, maybe with a more universal way.

**Comment by fengyehong** [comment]
Before move list_tasks to `/v2/tasks` endpoint, everything works fine without a leading slash

**Comment by solarkennedy** [comment]
I am convinced. Can you rebase after your other related PR and I'll merge?

**Comment by fengyehong** [comment]
Rebased

**Comment by solarkennedy** [comment]
Thank you for rebasing, I know that can be frustrating sometimes.

**Pull request merged**
