### PR TITLE
Fix deployments parsing

### PR DESCRIPTION
**Pull request by Rob-Johnson**
fixes parsing of deployments endpoint. duplicate of #40

### CODE REVIEW

**Comment by Rob-Johnson** [comment]
fwiw, here's the failing output from the test:

```
cls = <class 'marathon.models.deployment.MarathonDeploymentAction'>, attributes = [{'action': 'ScaleApplication', 'app': '/test'}]

    @classmethod
    def from_json(cls, attributes):
        """Construct an object from a parsed response.

            :param dict attributes: object attributes from parsed response
            """
>       return cls(**{to_snake_case(k): v for k,v in attributes.items()})
E       AttributeError: 'list' object has no attribute 'items'
```

**Comment by Rob-Johnson** [comment]
let's get travis running the unit tests now we have some, too.

**Comment by solarkennedy** [comment]
This is great! Having a "place to put this" is a great thing.

An itest would be cool too, but this is hard to catch (for us at Yelp too!)

**Comment by solarkennedy** [comment]
Thanks!

**Pull request merged**
