### PR TITLE
Release 0.6.16, fixes #38

### LINKED ISSUE #38: New release for 8.2 compatibility
I thought that the latest version of marathon-python covered the latest 0.8.2, but it doesn't fully, and I need this commit:
https://github.com/thefactory/marathon-python/commit/de5c91ae7dc158f53b5c46d3c39a6e6f13c775d6

I'm am going to expand our integration tests to catch this, but till then can you make a new release for better compatibility for 0.8.2 that I can pull down?

### PR DESCRIPTION
**Pull request by solarkennedy**
I'm blocked on upgrading to marathon 8.2. I would like to do whatever I can to help get this release out?
(I don't really want to pin to a particular sha)

### CODE REVIEW

**Comment by g----** [comment]
Please merge @solarkennedy's commit. We really need this. Thank you:)

**Comment by mbabineau** [comment]
Sorry for the delay, here we go: 42abbbe701b44f92ed7c034d848186340a43d6c6

**Comment by solarkennedy** [comment]
Thanks!

**Comment by g----** [comment]
Thanks:)

**Pull request closed without merging**
