### PR TITLE
Add raw_data option for event_stream method

### PR DESCRIPTION
**Pull request by fengyehong**
This is just a proposal. If you just store events in a message queue and leave it to other consumers, then there is no need to parse the event data as MarathonEvent object

### CODE REVIEW

**Comment by solarkennedy** [comment]
How but just `raw` instead of `raw_data`? But Yea I would merge

**Comment by fengyehong** [comment]
updated and rebased

**Comment by solarkennedy** [comment]
Why is travis not testing this?...

**Comment by fengyehong** [comment]
> Why is travis not testing this?...

No idea

**Comment by solarkennedy** [comment]
I've asked travisci and @mbabineau to turn it off and on again.

In the mean time can you run the tests locally via tox and confirm that they pass?

**Comment by fengyehong** [comment]
In fact, I have received Travis build success email for my forked repo

https://github.com/fengyehong/marathon-python/branches

**Pull request merged**
